### ISSUE TITLE
can not compile v0.7.0-dev on Linux

### ISSUE THREAD

**Issue by tissatussa** [codedeliveryservice/Reckless#49]
### Bug description

at first i did a `git clone` of your newest source files, but then compiling failed like this :

```
$ cargo rustc --release -- -C target-cpu=native
   Compiling reckless v0.7.0-dev (/home/roelof/Compiled/Reckless-main)
error: couldn't read /home/roelof/Compiled/Reckless-main/networks/model.nnue: No such file or directory (os error 2)
  --> src/nnue.rs:82:63
   |
82 | static PARAMETERS: Parameters = unsafe { std::mem::transmute(*include_bytes!(env!("MODEL"))) };
   |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `reckless` (bin "reckless") due to 1 previous error
```

i found the missing `model.nnue` file in your release source code ZIP and copied it into my folder tree. Then i get another error :

```
$ cargo rustc --release -- -C target-cpu=native
   Compiling reckless v0.7.0-dev (/home/roelof/Compiled/Reckless-main)
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> src/nnue.rs:82:42
   |
82 | static PARAMETERS: Parameters = unsafe { std::mem::transmute(*include_bytes!(env!("MODEL"))) };
   |                                          ^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `[u8; 197378]` (1579024 bits)
   = note: target type: `Parameters` (3158032 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `reckless` (bin "reckless") due to 1 previous error
```

i have no clue how to solve this ..

[ i'm on Xubuntu 22.04 ]

### Reproduction steps

see above

### Expected behavior

see above

### Operating system

Linux

### Version

v0.7.0 dev

### Additional context

do i have the proper Rust / Cargo version ?  How to verify this ?

**Comment by codedeliveryservice** [comment]
Thank you for opening an issue.
The NNUE model file has been moved to the [Reckless Networks][reckless-networks] repository since binary files aren't part of the engine's source code. The model you were attempting to use has a different architecture, making it incompatible.
I've updated the [Building from source][build] section to include the necessary build instructions.
Please let me know if you encounter any problems or need further clarification.

[reckless-networks]: https://github.com/codedeliveryservice/RecklessNetworks
[build]: https://github.com/codedeliveryservice/Reckless?tab=readme-ov-file#building-from-source

**Comment by tissatussa** [comment]
great info .. i just copied that newer `model.nnue` into the `networks` folder (not using the `.sh` script) and compiling went well : i got a working binary of 1.7 Mb and it runs fine in CuteChess.
